#! /bin/sh

picom &
polybar &
~/.fehbg &
setxkbmap dk &
xsetroot -cursor_name left_ptr &


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         5
bspc config window_gap          12
bspc config focused_border_color	'#90A383'
bspc config active_border_color		'#4b703c'
bspc config normal_border_color 	'#4b703c'	


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
#bspc rule -a kitty state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
